---
- name: Ensure dirs
  file: 
    path: "{{ item }}"
    owner: "root"
    group: "nginx"
    mode: 0750
    state: directory
  with_items:
    - "{{ site_web_dir }}"
    - "{{ site_log_dir }}"

- name: Copy default index file
  template: 
    src: index.html.j2
    dest: "{{ site_web_dir }}/index.html"
    owner: "root"
    group: "nginx"
    mode: 0750
  when: site_git_repo is not defined

- name: Deploy from repo
  git:
    repo: "{{ site_git_repo }}"
    dest: "{{ site_web_dir }}"
    update: yes
    force: yes
    accept_hostkey: yes

  when: site_git_repo is defined

- name: Install nginx site configuration file
  template: src=nginx-site.conf.j2 dest=/etc/nginx/conf.d/{{ site_host }}.conf
  notify: Reload nginx      
