---
- name: Install and configure phpci (as user)
  include: as_user.yml
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Create build cron
  cron:
    user: "{{ phpci_app_name }}"
    job: "/usr/bin/php {{ phpci_app_dir }}/console phpci:run-builds"
    minute: "*"
    hour: "*"
    day: "*"
    weekday: "*"
    month: "*"
    name: "{{ phpci_app_name }}_run_builds"
    state: present
