---
- name: Install php-ci using composer
  command: /usr/local/bin/composer create-project block8/phpci application --keep-vcs --no-dev
  args:
    chdir: "~{{ phpci_app_name }}"
    creates: "{{ phpci_app_dir }}/console"
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Create log directory
  file: 
    path: "{{ phpci_app_dir }}/logs"
    state: directory
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Symlink log directory
  file:
    src: "{{ phpci_app_dir }}/logs"
    path: "~{{ phpci_app_name }}/logs/phpci" 
    state: link
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Copy logger config
  copy: 
    src: "loggerconfig.php"
    dest: "{{ phpci_app_dir }}/loggerconfig.php"
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Install php-ci composer deps
  command: /usr/local/bin/composer install 
           --no-scripts 
           --no-dev 
           --optimize-autoloader 
           --prefer-dist 
           --no-progress 
           --no-interaction
  args: 
    chdir: "{{ phpci_app_dir }}"
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Install extra composer packages
  command: /usr/local/bin/composer require
           --update-no-dev
           --no-progress
           --no-interaction
           --prefer-dist
           {{ phpci_extra_packages|join(' ') }}
  args:
    chdir: "{{ phpci_app_dir }}"
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Ensure executables
  file:
    path: "{{ phpci_app_dir }}/{{ item }}"
    mode: 0755
  with_items:
    - console
    - daemonise
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"
  
- name: Setup php-ci
  command: ./console phpci:install
           --db-host "localhost" 
           --db-name "{{ phpci_app_name }}" 
           --db-user "{{ phpci_app_name }}" 
           --db-pass "{{ phpci_db_pass }}"
           --admin-name "{{ phpci_admin_name }}"
           --admin-pass "{{ phpci_admin_pass }}"
           --admin-mail "{{ phpci_admin_email }}"
           --url "http://{{ phpci_hostname }}/"
  args:
    chdir: "{{ phpci_app_dir }}"
    creates: "{{ phpci_app_dir }}/PHPCI/config.yml"
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Create php-ci db schema
  command: ./console phpci:update
  args: 
    chdir: "{{ phpci_app_dir }}"
  sudo: yes
  sudo_user: "{{ phpci_app_name }}"

- name: Create build cron
  cron:
    user: "{{ phpci_app_name }}"
    job: "/usr/bin/php {{ phpci_app_dir }}/console phpci:run-builds"
    minute: "*"
    hour: "*"
    day: "*"
    weekday: "*"
    month: "*"
    name: "{{ phpci_app_name }}_run_builds"
    state: present
