b8:
    database:
        servers:
            read: localhost
            write: localhost
        name: {{ php_ci_app_name }}
        username: {{ php_ci_app_name }}
        password: {{ php_ci_db_pass }}
phpci:
    url: 'http://{{ php_ci_hostname }'