---
- name: Create user 
  user:
    state: present
    name: "{{ pool_user }}"
    home: "{{ pool_home }}"
    createhome: yes

- name: Create log directory
  file: 
    path: "{{ pool_log_dir }}"
    owner: "{{ pool_user }}"
    group: "nginx"
    mode: 0700
    state: directory
  
- name: Install pool config
  template:
    src: pool.conf.j2
    dest: /etc/php-fpm.d/{{ pool_name }}.conf
  notify: Restart php-fpm
 

  
