---
- name: Install mysqld package
  yum: name={{ item }} enablerepo=remi state=installed
  with_items:
    - mariadb-server
    - MySQL-python

- name: Install mysqld config
  template: src=my.cnf.j2 dest=/etc/my.cnf.d/server.cnf
  notify: 
    - Restart mysql

- name: Ensure mysqld dirs
  file: 
    path: /var/log/mysql
    owner: mysql
    group: mysql
    mode: 0755
    state: directory
  with_items:
    - /var/log/mariadb
    - /var/run/mariadb

- name: Start and enable mysqld service
  service: name=mariadb state=started enabled=true

- name: Open mysql ports in firewall
  firewalld: service="mysql" zone=public permanent=true state=enabled
  when: mysql_open_to_world
  notify: Reload firewalld
