export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="blinks"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git colorize symfony2 npm bower composer cp)

source $ZSH/oh-my-zsh.sh

export PATH="/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export LANG=en_US.UTF-8
export EDITOR="nano"

alias su='sudo su'

